name: kitchen_tool_scanner
description: "A Flutter Kitchen Tool Scanner App with On-Device AI Detection and CustomPainter 3D Tutorials."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1
  shared_preferences: ^2.5.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/ssd_mobilenet.tflite
    - assets/models/labels.txt
    - assets/models/LICENSE-2.0.txt
    - assets/models/MODEL_CARD.md
